apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
spec:
  selector:
    app: kafka-consumer
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: app
          image: 245522776103.dkr.ecr.us-east-1.amazonaws.com/meds_connected_devices_kafka_consumer:0.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
